FROM python:3.11-slim

WORKDIR /app

 

# Копируем requirements.txt
COPY requirements.txt .

# Обновляем pip
RUN pip install --upgrade pip

RUN pip install -r requirements.txt

# Копируем исходный код
COPY . .


CMD ["fastapi", "dev", "main.py", "--port", "8000"]